# Generated by Django 5.0.6 on 2024-06-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('marca', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=20)),
                ('anno', models.PositiveIntegerField(max_length=4)),
                ('num_puertas', models.PositiveIntegerField(max_length=5)),
                ('motor', models.BooleanField(verbose_name=True)),
                ('activo', models.IntegerField()),
                ('id_auto', models.ForeignKey(db_column='idAuto', on_delete=django.db.models.deletion.CASCADE, to='Tienda_Repuestos.auto')),
            ],
        ),
    ]
