# Generated by Django 5.0.6 on 2024-06-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='anno',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='num_puertas',
            field=models.PositiveIntegerField(),
        ),
    ]
